name: capbuilder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: update pkg and make aircrack
         run: |
              sudo apt update -y
              sudo apt install git aircrack-ng -y

       - name: Run wordlist maker
         run: |
              sudo python3 hy.py

       - name: start cracking
         run: |
              sudo aircrack-ng -w pass.txt mp.cap
